logging:
  level:
    org.springframework: DEBUG
    pt.jmnpedrosa.samples.springbootmq: DEBUG
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE
  file: D:/logs/spring-boot-mq-sample.log
    
server.port: 8080

# These are dummy values.
# Replace them with your own server implementation.
jms:
  sender:
    connection:
      host_name: http://localhost/
      port: 1414
      user_name: username
      password: password
      mq:
        transport_type: 1
        queue_manager: QUEUENAME
        channel: CHANNELNAME
    queue: QUEUENAME
    encoding: 284

# listening interval between messages
message.interval.secs: 5